### ISSUE TITLE
Wish: check validity of optimality input

### ISSUE THREAD

**Issue by ugroempi** [tylermorganwall/skpr#32]
Hi Tyler,
I just spent (a little) time to find out what the error message "object 'rowindex' not found" means. It came up because I wrote "alias" instead of "Alias" for the optimality criterion. Would be nice if there were a more informative error message.
Best, Ulrike

**Comment by tylermorganwall** [comment]
Hi Ulrike,
Thank you for the find. I just pushed an update that makes the optimality criteria input case0-insensitive, and now it throws a more informative error when the criterion is not recognized.
