### ISSUE TITLE
Bug in version 0.46.0?

### ISSUE THREAD

**Issue by ugroempi** [tylermorganwall/skpr#40]
Hi Tyler,

I'm curious about the new functionality and installed the latest skpr version. However, running the following code gave me an error:
`cand <- DoE.base::fac.design(nlevels=c(2,2,2,3,4,4))`
`gen_design(cand, model=~(A+B+C+D+E+F)^2, trials=96)`

The error message (translated from German):
Error in .Call(`_skpr_genOptimalDesign`, initialdesign, candidatelist,  : 
  Wrong number of arguments (9), expected 8 for '_skpr_genOptimalDesign'

Did something go wrong with my use of skpr or my installation, or is something wrong in skpr?

Best, Ulrike

**Comment by tylermorganwall** [comment]
Hi Ulrike,

Are you on a Windows machine? Try deleting skpr in your libraries folder manually and reinstalling from github. I have found that the dll file often doesn't uninstall when removing a package within R, which would cause the updated compiled code not to work.

**Comment by ugroempi** [comment]
Thanks, I'll try that tomorrow!
Best, Ulrike

**Comment by ugroempi** [comment]
That was it!
