### ISSUE TITLE
Split-Plot Alias Optimal design

### ISSUE THREAD

**Issue by StevenCHowell** [tylermorganwall/skpr#44]
I just came across this package.  As far as I could tell (including looking at the [CRAN Experiment Design task view](https://cran.r-project.org/web/views/ExperimentalDesign.html), `skpr` is the only R-package that creates Alias-optimal experiments designs.

Do you know what would be required to support split-plot functionality for Alias optimal designs?  Is this a feature you would like to support?

**Comment by tylermorganwall** [comment]
Hi Steven,

skpr does already support Alias-optimal split-plot designs--just not currently in the GUI. You can generate split-plot Alias-optimal designs by calling gen_design in code and setting `optimality = "ALIAS"`, as well as providing the required split-plot design arguments. I'll activate support for Alias-optimal designs in the GUI in the next update.

**Comment by StevenCHowell** [comment]
This is great to hear.  I am actually more inclined to use a scripted workflow.  I saw the message about it not being supported and wanted to ask.

I am relatively new to R but this looked like the best scripted option for DOE.  Scripting JMP was not promising.  I am impressed by the capabilities already included within this project.  I would be interested to see a roadmap or list of future features/capabilities you would like to add.  

Have you considered adding the package to conda-forge?  Would you mind if I looked into what it would take to do that?

**Comment by tylermorganwall** [comment]
Glad to hear it. The feature set is now mostly driven by user requests--most of the original planned features have been implemented. If you have something in particular in mind, post it as a feature request and I'll see if I can add it.

I have not considered adding it to conda-forge, but I will look into it.

**Comment by StevenCHowell** [comment]
I think the R version I have access to, Microsoft R Open 3.4.3, is actually a problem.  When I run `install.packages("skpr")` I get the package at [https://mran.microsoft.com/snapshot/2017-09-01/bin/windows/contrib/3.4/skpr_0.35.1.zip](https://mran.microsoft.com/snapshot/2017-09-01/bin/windows/contrib/3.4/skpr_0.35.1.zip) which was before split-plot design supported Alias optimization.

https://github.com/tylermorganwall/skpr/blob/772088804cd5963d6a3c60fbcb4e6c9995728bae/NEWS#L56-L69

I am trying to resolve this.  

What R version does the current release require?  Were there significant R changes that introduced incompatibilities?  I may just need to tell R I want a more recent version of `skpr`.

**Comment by tylermorganwall** [comment]
See:

https://mran.microsoft.com/#change-repos

>  To change this default repository, choose one of the following:
>  * Update the .Rprofile to point to a different snapshot date:options(repos = c(CRAN = "https://mran.revolutionanalytics.com/snapshot/YYYY-MM-DD"))
>  * Or, set the default repository to a standard CRAN mirror that refreshes daily, for example:options(repos = c(CRAN = "https://cran.revolutionanalytics.com"))

>  However, if you just need a few packages from a different date, we recommend you keep the default repository date configured for Microsoft R Open and use the checkpoint function to get those packages. For the argument to the checkpoint() function, choose a date on or after September 17th, 2014 (say, yesterday's date), and checkpoint will install all packages required by your project as they were at midnight UTC on the date you specified. Learn more about checkpoint.

**Comment by StevenCHowell** [comment]
I tried using the `checkpoint()` function and it ended up changing what seemed like 50 packages.  I was hoping to limit the updates to only a few but I don't think it is worth the trouble.  I will revert to that solution.

**Comment by tylermorganwall** [comment]
You can also install directly from the github page (you need RTools installed), and reference a single commit if you want reproducibility:

```r
install.packages("devtools")
devtools::install_github("tylermorganwall/skpr", ref="772088804cd5963d6a3c60fbcb4e6c9995728bae")
```

**Comment by StevenCHowell** [comment]
I tried that after `checkpoint()`.  There was an issue with the `promises` package not being available.  It did work when I used `checkpoint()` so I will go that route.

**Comment by StevenCHowell** [comment]
To confirm, in the `skprGUI`, for version 0.49.1, selecting Alias optimal design with a hard-to-change factor outputs the error: 
> "Hard-to-change factors are not currently supported for Alias, T, and G optimal designs."

This is only for the GUI?  Could this be causing my problem with disallowed combinations, issue #45?
