### ISSUE TITLE
gen_design generated repeated samples for a d-optimal design

### ISSUE THREAD

**Issue by rodrigorpgsc** [tylermorganwall/skpr#51]
Hi skpr team,

I tried to use gen_design function to generate a D optimal design but the output sounds weird to me. I have a process and I`d like to explore 3 factors, but the process have a lot of constraints so I provide a candidate set for the function. I have 20 possibilities, but only have money/time for 12 samples.

Let me paste the code here
config_machine<- matrix(c(5,               3,      20,
             5,               3,    2210.,
             5,               1,    1753.,
             4,               3,    2105.,
             4,              1,    2022.,
             4,               1,     874, 
             5,               3,    2001.,
             4,               3,     979, 
             5,               3,     811, 
             5,               2,     750, 
             4,               1,     853, 
             4,               2,    1836.,
             4,               3,     895, 
             5,               3,     100, 
             5,               2,     832, 
             4,               2,    2043.,
             4,               3,    1795.,
             4,              1,    1815.,
             4,              2,     937, 
             4,               3,    1920.),3,20)
config_machine <- t(config_machine)
colnames(config_machine) <- c('X1','X2','X3')
df <- as.data.frame(config_machine)
design <- gen_design(candidateset = df, model = ~X1 + X2 + X3, trials = 12,repeats = 1000)
design

But the output will show some like this

  X1 X2   X3
1   5  3   20
2   5  3 2210
3   5  3   20
4   4  3 2105
5   5  1 1753
6   5  1 1753
7   5  3 2210
8   4  3 2105
9   4  1  853
10  4  3 2105
11  5  3   20
12  4  1  853

Sounds very weird to me the sample 1,3 and 11 **are the same point(5,3,20)**! I only have 12 samples but the function is wasting my samples using repeated measures. What is my mistake? I tried to read the documentation but didn`t find any tip. 

Regards

**Comment by GeorgeMKhoury** [comment]
Looks ok to me. With the model you specified, the D-optimal design is going to be at the edges of your candidate set, that is, with the factors taking their highest/lowest values. For the model X1 + X2 + X3, there are only 8 possibilities: 

(low, low, low), 
(low, low, high), 
(low, high, low), 
(low, high, high), etc. 

So you are going to see repeated points whenever the trials is higher than 8.

You candidate set has a bunch of restrictions, so this structure isn't obvious on first glance, but if you order the design you can see that this is what skpr did - it took the lowest/highest values for each factor.

**Comment by tylermorganwall** [comment]
Yes, George is correct. A D-optimal design with continuous factors and no higher-order terms will only pick points on the edges of the candidate set, as that minimizes the volume of the confidence ellipsoid of the regression estimates. If you want to ensure your design covers the parameter space instead, look into space-filling designs (DiceDesign and LatticeDesign are two packages that might be of help).
