### ISSUE TITLE
CLEANUP: Drop argument `ncores` from doParallel::registerDoParallel(cl, cores = numbercores)

### ISSUE THREAD

**Issue by HenrikBengtsson** [tylermorganwall/skpr#56]
FYI, when you specify argument `cl` as in:

https://github.com/tylermorganwall/skpr/blob/529fd19394f7fab669dfaa7b7c3890b2140c63ad/R/gen_design.R#L928-L929

argument `ncores` is completely ignored. If you look at the code, there's never a case where both a needed, i.e. specify either-or.

**Comment by GeorgeMKhoury** [comment]
It's true. I can fix this if you haven't already.

**Comment by tylermorganwall** [comment]
Fixed in ab0cc7dadeb5077aa4f02c305559868a6cf4c44c
