### ISSUE TITLE
scaling of the search time with size of the candidate set

### ISSUE THREAD

**Issue by comatrion** [tylermorganwall/skpr#64]
The time to generate a D-optimal design seems to scale approximately linearly with the size of the candidate set. 

If the initial candidate set contains all possibilities, that scaling becomes exponential in the number of factors/levels. 

However for larger numbers of factors/levels, the difference in terms of optimality (and e.g. low estimate correlations ) between using the full candidate set and a smaller, random sample, looks marginal.

I'm wondering why that is and if there could be some workable sampling strategy to generate larger designs in a shorter time.

The attached script (raw output attached) generates a
* D-Optimal design
* 8 x 5-level categorical factors
* main effects only
* 400 runs

The script runs `gen_design` multiple times, varying the initial candidate set.  

Results are in the table below.

```
Size    Time (s)        D Optimality    Off-diagonal correlation        
                                        Median  Max
5000    33.1            99.8896         0.00455 0.0273
10000   54.0            99.9021         0.00406 0.0314
20000   112.5           99.9092         0.00331 0.0270
50000   227.0           99.9254         0.00261 0.0329
100000  565.6           99.9336         0.00240 0.0218
200000  1287.1          99.9498         0.00020 0.0217
390625  1676.4          99.9498         0.00024 0.0231
```

In each run (apart from the last) a random sample is selected from the "full" candidate set generated by `expand_grid`. In the final run, the full candidate set is used.  As the size of the sample increases, the optimality increases slightly and the median off-diagonal correlation falls. That's expected because the search algorithm is able to explore a greater number of possibilities in each run. However, the search time increases roughly linearly with the sample size, and the difference between using all possibilities and a smaller, random sample looks quite small in relation to the extra time.

Versions

MacBook Pro, 32GB, 8-Core, 2.3 Ghz Intel Core i9
R 4.0.5
skpr 1.0.0

Files

[output.txt](https://github.com/tylermorganwall/skpr/files/7075852/output.txt)
[bench.R.txt](https://github.com/tylermorganwall/skpr/files/7075853/bench.R.txt)
[skpr.xlsx](https://github.com/tylermorganwall/skpr/files/7075854/skpr.xlsx)

**Comment by GeorgeMKhoury** [comment]
Well, random designs are often surprisingly good, and using a random subset of the candidate set is kind of like a random design.  I think that's part of what's going on here. Also, this is a pretty good situation for a random design:
1) you are using 400 runs to estimate a 33-parameter model, so it's pretty likely that you're going to get enough of the design space covered to get decent parameter estimates, even with a fairly small subset of the candidate set.  2) With a main-effects model, there's no special structure needed in the design points - you just need to cover all the factor settings, in an uncorrelated way - so random sampling will perform well.

As for a more general procedure to speed things up, you could always try using a small subset of the candidate set and see what design you get. If it's good enough, then it's good enough and you are done! If it's not, increase the size of the subset and try again.

**Comment by comatrion** [comment]
Thanks. 

I read that the coordinate exchange algorithm (CEA) [1] has a faster execution time compared to the modified Federov algorithm that is the default in `skpr`.  Would CEA be applicable?  Or is there be some functionality of `skpr` that rules out CEA?

[1] R.K. Meyer and C.J. Nachtsheim. The coordinate-exchange algorithm for constructing exact optimal experimental designs. Technometrics, 37(1):60–90, 1995.

**Comment by tylermorganwall** [comment]
Yes, the coordinate exchange is faster, but it's limited to factorial design regions (e.g. no disallowed combinations or mixture designs). skpr's point exchange approach allows the user to constrain the candidate set via filtering out disallowed combinations, which is much harder to implement with a coordinate exchange approach.

To speed up your search, you might try adjusting the `k` argument in `gen_design()`.

From the docs:

"This exchanges only the k lowest variance runs in the design at each search iteration.  Lower numbers can result in a faster search, but are less likely to find an optimal design.  Values of ‘k >= n/4‘ have been shown empirically to generate similar designs to the full search.  When ‘k == trials‘, this results in the default modified Federov’s algorithm"

**Comment by comatrion** [comment]
Thanks, I will try that.
