### ISSUE TITLE
D-optimality (incorrectly?) low for large design

### ISSUE THREAD

**Issue by antonyebrown** [tylermorganwall/skpr#69]
I have a large test design with several disallowed combinations that is showing a suspiciously low D-optimality. I took the design output and evaluated it in JMP, and this resulted in a large difference.  Here is the code (please forgive the nonsense descriptors):

    set.seed(4)

    factorial = expand.grid(Lion = as.factor(c("L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", "L9")),
    Bear = as.factor(c("B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9")), 
    Tiger = as.factor(c("T1", "T2", "T3", "T4", "T5", "T6", "T7")), Monkey = as.factor(c("M1", "M2")))

    factorial = subset(factorial, 
                        !(Lion %in% c("L4") & Monkey %in% c("M1")) &
                        !(Lion %in% c("L5") & Monkey %in% c("M1")) &
                        !(Lion %in% c("L6") & Monkey %in% c("M1")) &
                        !(Lion %in% c("L7") & Monkey %in% c("M1")) &
                        !(Lion %in% c("L8") & Monkey %in% c("M1")) &
                        !(Lion %in% c("L9") & Monkey %in% c("M1")))

    optdesign = gen_design(candidateset = factorial, model = ~(Lion + Bear + Tiger + Monkey + 
    Lion:Bear + Lion:Tiger +Bear:Tiger + Bear:Monkey + Tiger:Monkey), trials=1215, repeats = 100, parallel = TRUE)

    get_optimality(optdesign)

This results in the following:
D Efficiency: 2.757065
I (Avg Pred. Var.): 0.2074947
A Efficiency: 78.53839
G Efficiency: Not Computed 

Importing <code>optdesign</code> into JMP gives the following:
D Efficiency: 92.3571
I (Avg Pred. Var.): 0.207489
A Efficiency: 78.54045
G Efficiency: 54.57657

So the only real difference is the D Efficiencies. The FDS and Correlation plots match from both as well.

Am I doing something wrong, or is there a problem we run into when test designs exceed a certain size, or the number of disallowed combinations is too great? Experimenting with smaller and simpler D-Optimal designs gives roughly the same values of D Efficiency for both skpr and JMP.

**Comment by tylermorganwall** [comment]
Looks like package is running into numerical precision issues when calculating the Cholesky decomposition to get the D efficiency value (the problem stems from the large number of runs and model terms in the design). I switched the underlying calculation to use a more precise method that should match JMP's output (so this is fixed in commit ef2b6f1c879f420bb9445019a336a7b1b1eb4fa0).

**Comment by tylermorganwall** [comment]
And thanks for the bug report!
