### ISSUE TITLE
Input design when using gen_design for design augmentation...

### ISSUE THREAD

**Issue by peterj00** [tylermorganwall/skpr#72]
Thanks for a nice package!  However, it appears to me that, for design augmentation purposes, the gen_design function requires an input design that was originally generated by gen_design.   But, I may have a design that was not generated by gen_design (e.g. an odd or broken design) that I want to augment.  Is there a way I can get gen_design to augment a design that it did not originally create?  If it was a standard design I want to augment, then perhaps I can get gen_design to re-create it, but if its an odd or broken design I need to augment, then I am not sure how to proceed via gen_design.  (It appears that gen_design requires all of the R attributes attached to an original design, created by gen_design, in order to be able to augment it.  Is that correct?)

**Comment by tylermorganwall** [comment]
Hi Peter,

Check the latest version on github (v1.1.7) where this is fixed and see if it solved your issue: it was a single line that just needed to be changed checking for that attribute.

**Comment by tylermorganwall** [comment]
I am fairly sure this is closed—if it isn't, post the code that still doesn't work and I'll reopen the issue.
