### ISSUE TITLE
[Feature Request] Pareto Chart

### ISSUE THREAD

**Issue by mr-september** [tylermorganwall/skpr#74]
I've seen this recently used at a conference in combination with DoE, but it was in a paid software suite. Basically, it ranks factors and also estimates a cut-off by Bonferroni and/or t-value limits. 

Unfortunately that work is yet unpublished, but I've found other examples, i.e.

Antunes Barros, A.A., da Rocha Cardoso, A.P., Rodrigues, A.C. et al. Optimizing enzymatic dyeing of wool and leather. _SN Appl. Sci._ 1, 1232 (2019). [https://doi.org/10.1007/s42452-019-1241-6](https://link.springer.com/article/10.1007/s42452-019-1241-6)

![image](https://user-images.githubusercontent.com/45350177/205060854-dd2d1e39-bdd8-4c58-bbc5-6fd02c9ad077.png)

Just putting in a feature request for consideration :)

**Comment by tylermorganwall** [comment]
I believe this is an application on the analysis side (after data collection) rather than the generation and evaluation of the experimental design, which is skpr's purpose. Feel free to chime in if I've misinterpreted the paper.
