### ISSUE TITLE
Cannot get the updated criteria 

### ISSUE THREAD

**Issue by Lefty2021** [tylermorganwall/skpr#79]
Once you add some points manually on the design(for whatever reason) you cannon get the updated criteria (eg D-optimal values). In more specific in a D-optimal design I added some central points and I would like to see the effect of that addition.

**Comment by tylermorganwall** [comment]
Pass the design to `eval_design()` and then pass the power output to the `get_optimality()` function to obtain updated optimality values. 

See https://tylermorganwall.github.io/skpr/reference/get_optimality.html
